//! The JSON Schema projection — the shape the model sees.
//!
//! Maps to: zod/v4 `toJSONSchema` (consumed via `utils/zodToJsonSchema.ts`).
//! The output shape is taken from golden fixtures generated by running real
//! zod v4 (`fixtures.json`), not from the JSON Schema spec or from schemars'
//! habits. Every shape decision below cites the fixture that pins it.

use super::error::bound_to_json;
use super::schema::Schema;
use serde_json::{Map, Value, json};

/// The draft marker zod/v4 writes as the first key of every top-level
/// projection (`target: 'draft-2020-12'` is `toJSONSchema`'s default).
pub const JSON_SCHEMA_DRAFT: &str = "https://json-schema.org/draft/2020-12/schema";

/// Maps to: zod/v4 `toJSONSchema(schema)`.
///
/// The draft marker is attached at the top level ONLY — nested subschemas carry
/// no `$schema`, and it leads the key order. `api.ts:160` hands this object
/// straight to the API as a tool's `input_schema`, so the envelope is on the
/// wire, not decoration: `z.any()` projects to `{}` and still ships
/// `{"$schema": …}`.
pub fn to_json_schema(schema: &Schema) -> Value {
    let mut out = Map::new();
    out.insert("$schema".to_string(), json!(JSON_SCHEMA_DRAFT));
    if let Value::Object(inner) = project(schema) {
        out.extend(inner);
    }
    Value::Object(out)
}

fn project(schema: &Schema) -> Value {
    match schema {
        // `.describe()` surfaces as `description`, inner shape otherwise
        // unchanged (fixture: describe.schema).
        Schema::Describe(inner, text) => {
            let mut out = project(inner);
            if let Some(obj) = out.as_object_mut() {
                // zod puts description before the type keys; the fixtures pin
                // content, not key order, so insertion order is free.
                obj.insert("description".to_string(), json!(text));
            }
            out
        }
        // preprocess is invisible in the projection (fixture:
        // read_input_semantic_number — offset shows the inner integer schema).
        Schema::Preprocess(_, inner) => project(inner),
        // refine is invisible in the projection (oracle: refine.schema passes
        // straight through to the inner string). catch and check are equally
        // transparent: the tolerance / post-check never enters the schema.
        Schema::Refine(_, _, inner)
        | Schema::SuperRefine(_, inner)
        | Schema::CatchUndefined(inner)
        | Schema::CatchUndefinedWith(_, inner)
        | Schema::Check(_, inner) => project(inner),
        // zod/v4 throws "Transforms cannot be represented in JSON Schema" on a
        // transform; the carrier surfaces that refusal rather than inventing a
        // shape. Callers that need a schema must not put a transform in the
        // projected path.
        Schema::Transform(_, _) => {
            json!({"$error": "Transforms cannot be represented in JSON Schema"})
        }
        // optional does not alter the type shape (fixture:
        // read_input_semantic_number — offset is integer, not a union).
        Schema::Optional(inner) => project(inner),
        // nullable projects as `anyOf: [inner, {"type":"null"}]` (oracle:
        // nullable.schema).
        Schema::Nullable(inner) => {
            json!({"anyOf": [project(inner), {"type": "null"}]})
        }
        // `.default()` surfaces as a `default` key AND leaves the field
        // required (fixture: default_absent — `{"default":"d","type":"string"}`
        // and `required:["a"]`).
        Schema::Default(inner, fill) => {
            let mut out = project(inner);
            if let Some(obj) = out.as_object_mut() {
                obj.insert("default".to_string(), fill.clone());
            }
            out
        }

        // zod writes the checks alongside `type` (oracle: string_min /
        // string_regex / string_url). `pattern` carries no `/` delimiters here,
        // unlike the issue's own `pattern` field.
        Schema::String {
            check_order,
            min_length,
            length,
            starts_with,
            ends_with,
            pattern,
            format,
            ..
        } => {
            let mut obj = Map::new();
            obj.insert("type".into(), json!("string"));
            if let Some(n) = min_length {
                obj.insert("minLength".into(), json!(n));
            }
            // `.length(n)` projects BOTH bounds (oracle: string_length_ok).
            if let Some(n) = length {
                obj.insert("minLength".into(), json!(n));
                obj.insert("maxLength".into(), json!(n));
            }
            let mut patterns = Vec::new();
            for check in check_order {
                match check {
                    super::schema::StringCheck::Prefix => {
                        if let Some(p) = starts_with {
                            patterns.push(format!("^{}.*", regex_escape(p)));
                        }
                    }
                    super::schema::StringCheck::Suffix => {
                        if let Some(p) = ends_with {
                            patterns.push(format!(".*{}$", regex_escape(p)));
                        }
                    }
                    super::schema::StringCheck::Regex => {
                        if let Some(p) = pattern {
                            patterns.push((*p).to_string());
                        }
                    }
                    _ => {}
                }
            }
            if patterns.len() == 1 {
                obj.insert("pattern".into(), json!(patterns[0]));
            } else if patterns.len() > 1 {
                obj.insert(
                    "allOf".into(),
                    Value::Array(
                        patterns
                            .into_iter()
                            .map(|pattern| json!({"pattern":pattern}))
                            .collect(),
                    ),
                );
            }
            if let Some(f) = format {
                obj.insert("format".into(), json!(f.json_schema_format()));
            }
            Value::Object(obj)
        }
        Schema::Boolean => json!({"type": "boolean"}),
        Schema::Any => json!({}),
        Schema::Number {
            int,
            positive,
            nonnegative,
            min,
            max,
        } => {
            let mut obj = Map::new();
            if *int {
                // fixture: int.schema — safe-integer bounds, NOT a hand-added cap.
                obj.insert("type".into(), json!("integer"));
                obj.insert("minimum".into(), json!(-9007199254740991_i64));
                obj.insert("maximum".into(), json!(9007199254740991_i64));
            } else {
                obj.insert("type".into(), json!("number"));
            }
            if *positive {
                // fixture: read_input_semantic_number — a positive bound
                // REPLACES the safe-int negative minimum (limit has
                // exclusiveMinimum:0 and no minimum:-9007...).
                obj.insert("exclusiveMinimum".into(), json!(0));
                if *int {
                    obj.remove("minimum");
                }
            } else if *nonnegative {
                // fixture: offset — `minimum:0` replaces the safe-int minimum.
                obj.insert("minimum".into(), json!(0));
            }
            // `.min()` / `.max()` are inclusive, so they land on `minimum` /
            // `maximum` and override any safe-int bound (oracle: TaskOutputTool's
            // `timeout`, which is `.min(0).max(600000)`).
            if let Some(n) = min {
                obj.insert("minimum".into(), bound_to_json(*n));
            }
            if let Some(n) = max {
                obj.insert("maximum".into(), bound_to_json(*n));
            }
            Value::Object(obj)
        }
        Schema::Literal(v) => match v {
            Value::String(_) => json!({"type": "string", "const": v}),
            Value::Bool(_) => json!({"type": "boolean", "const": v}),
            Value::Number(_) => json!({"type": "number", "const": v}),
            _ => json!({"const": v}),
        },
        Schema::Enum(values) => json!({"type": "string", "enum": values}),
        Schema::Array {
            items,
            min_items,
            min_message: _,
            max_items,
        } => {
            let mut obj = Map::new();
            if let Some(n) = min_items {
                obj.insert("minItems".into(), json!(n));
            }
            if let Some(n) = max_items {
                obj.insert("maxItems".into(), json!(n));
            }
            obj.insert("type".into(), json!("array"));
            obj.insert("items".into(), project(items));
            Value::Object(obj)
        }
        Schema::Record(inner) => {
            // fixture: record_ok — zod names the key type explicitly.
            json!({
                "type": "object",
                "propertyNames": {"type": "string"},
                "additionalProperties": project(inner),
            })
        }
        Schema::RecordWithKey { key, value } => json!({
            "type": "object", "propertyNames": project(key), "additionalProperties": project(value),
        }),
        Schema::PartialRecord { keys, value } => {
            // zod spells "enum keys, all optional" as an anyOf of the enum
            // and an unsatisfiable `not: {}` arm (oracle: partial_record_ok).
            json!({
                "type": "object",
                "propertyNames": {
                    "anyOf": [{"type": "string", "enum": keys}, {"not": {}}]
                },
                "additionalProperties": project(value),
            })
        }
        // zod v4 projects BOTH `object` and `strictObject` with
        // `additionalProperties: false` (oracle: `z.toJSONSchema(z.object(...))`).
        // The difference is only in `safe_parse`: object strips stray keys from
        // the data, strictObject reports them. Loose objects are a separate
        // constructor (`z.looseObject`), which CC does not use here.
        Schema::Object(shape) => object_schema(shape, json!(false)),
        Schema::StrictObject(shape) => object_schema(shape, json!(false)),
        // `.passthrough()` admits unknown keys, which JSON Schema spells as an
        // empty subschema — `{}`, not `false` (oracle: MCPTool, which is
        // `z.object({}).passthrough()`).
        Schema::PassthroughObject(shape) => object_schema(shape, json!({})),
        Schema::Union(variants) => {
            json!({"anyOf": variants.iter().map(project).collect::<Vec<_>>()})
        }
        // zod projects a discriminated union as a plain `anyOf` of its object
        // variants (fixture: disc_union_ok) — the discriminator is implicit in
        // each variant's `const` tag.
        Schema::DiscriminatedUnion { variants, .. } => {
            json!({"anyOf": variants.iter().map(project).collect::<Vec<_>>()})
        }
    }
}

/// zod's own `escapeRegex` (core util), applied to a `.startsWith` prefix
/// before anchoring. The set includes `/` — the oracle's `./` prefix projects
/// as `^\.\/.*`, not `^\./.*`.
fn regex_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        if matches!(
            c,
            '.' | '*'
                | '+'
                | '?'
                | '^'
                | '$'
                | '{'
                | '}'
                | '('
                | ')'
                | '|'
                | '['
                | ']'
                | '\\'
                | '/'
        ) {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

fn object_schema(shape: &super::Shape, additional_properties: Value) -> Value {
    let mut properties = Map::new();
    let mut required = Vec::new();
    for (key, field) in shape.iter() {
        properties.insert((*key).to_string(), project(field));
        // A field is required unless it is optional or defaulted (fixtures:
        // read_input_semantic_number requires only file_path).
        if !is_optional(field) {
            required.push(json!(key));
        }
    }
    let mut obj = Map::new();
    obj.insert("type".into(), json!("object"));
    obj.insert("properties".into(), Value::Object(properties));
    // zod omits `required` entirely when nothing is required (oracle:
    // `z.toJSONSchema(z.object({a: z.string().optional()}))` has no such key).
    if !required.is_empty() {
        obj.insert("required".into(), Value::Array(required));
    }
    obj.insert("additionalProperties".into(), additional_properties);
    Value::Object(obj)
}

/// Whether a field is absent from `required`. zod's rule (oracle): only an
/// OUTER `.optional()` makes a field non-required — `x.default(d)` and
/// `x.optional().default(d)` both stay required, while `x.default(d).optional()`
/// does not. So we recurse the transparent wrappers and answer true only on
/// `Optional`; a bare `.default()` does not count.
fn is_optional(schema: &Schema) -> bool {
    match schema {
        Schema::Optional(_) => true,
        Schema::Describe(inner, _)
        | Schema::Preprocess(_, inner)
        | Schema::Refine(_, _, inner)
        | Schema::SuperRefine(_, inner)
        | Schema::Transform(_, inner)
        | Schema::CatchUndefined(inner)
        | Schema::CatchUndefinedWith(_, inner)
        | Schema::Check(_, inner)
        | Schema::Nullable(inner) => is_optional(inner),
        _ => false,
    }
}
