name: build-windows
on: workflow_dispatch
jobs:
    build:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v4
        - run: rustup update stable
        - run: cargo build --release --locked
          env:
            RUSTFLAGS: -C target-feature=+crt-static
        - uses: actions/upload-artifact@v4
          with:
            name: cometix-windows
            path: target/release/cometix.exe
